services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ma_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: ma_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
